<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "skfbalbums"
 *
 * Auto generated by Extension Builder 2017-08-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FB Albums',
    'description' => 'Show Facebook Page Albums and Photos on your site. No actual image files are downloaded. It uses image urls as given by Facebook.',
    'category' => 'plugin',
    'author' => 'Stefanos Karasavvidis',
    'author_email' => 'sk@karasavvidis.gr',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.15',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.99-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
